### PR TITLE
Use pod IP for host.name

### PR DESCRIPTION
**Pull request by ljufa**
Please use pod IP instead of name as k8s does not resolve pods by host name by default.
Before this change I was getting `UnknownHostException` exception :

`
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] [2018-10-09 13:57:13,622] ERROR Failed to send HTTP request to endpoint: http://infrastructure-messaging-cp-schema-registry-5f94dbc7d-4xb79:8081/subjects/asposepptgenerator-service.generate_ppt-value/versions (io.confluent.kafka.schemaregistry.client.rest.RestService)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] java.net.UnknownHostException: infrastructure-messaging-cp-schema-registry-5f94dbc7d-4xb79
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at java.net.Socket.connect(Socket.java:589)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at java.net.Socket.connect(Socket.java:538)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at sun.net.www.http.HttpClient.New(HttpClient.java:339)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at sun.net.www.http.HttpClient.New(HttpClient.java:357)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:172)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:229)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:320)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.forwardRegisterRequestToMaster(KafkaSchemaRegistry.java:526)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.registerOrForward(KafkaSchemaRegistry.java:389)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at io.confluent.kafka.schemaregistry.rest.resources.SubjectVersionsResource.register(SubjectVersionsResource.java:163)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at java.lang.reflect.Method.invoke(Method.java:498)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:183)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
[infrastructure-messaging-cp-schema-registry-5f94dbc7d-dxhmq cp-schema-registry-server] at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
`

### CODE REVIEW

**Comment by ljufa** [comment]
[clabot:check]

**Comment by maver1ck** [comment]
@ljufa Could you please add this also to Kafka Connect chart ?
Same problem there.

**Comment by maver1ck** [comment]
LGTM

**Comment by maver1ck** [comment]
Any idea why this is not merged ?

**Pull request merged**
