### PR TITLE
added nodePort support

### PR DESCRIPTION
**Pull request by survivant**
Signed-off-by: Sebastien Dionne <Sebastien.Dionne@bidgroup.ca>

for the issue : https://github.com/confluentinc/cp-helm-charts/issues/510

added NodePort support

### CODE REVIEW

**Comment by survivant** [comment]
@gAmUssA  to review.

**Comment by gAmUssA** [comment]
@survivant could you move this PR to https://github.com/confluent-helm-charts/cp-helm-charts 
Thank you

**Comment by survivant** [comment]
I'll do that tomorrow.

**Comment by survivant** [comment]
here the new PR : https://github.com/confluent-helm-charts/cp-helm-charts/pull/5

**Pull request closed without merging**
