### PR TITLE
Add minimum required config for KSQL to connect to Confluent Cloud

### PR DESCRIPTION
**Pull request by mplascencia-mb**
## What changes were proposed in this pull request?

Add example parameters for: 

- ksql.sink.replicas
- ksql.streams.replication.factor
- listeners
- security.protocol
- sasl.jaas.config

## How was this patch tested?

1. Uncommented the relevant configurationOverrides parameters and filled in with real values
2. set headless parameter to false
2. helm install on gke
4. Attached KSQL CLI to KSQL in GKE
5. Verified KSQL connection to Confluent Cloud Kafka

### CODE REVIEW

**Comment by mplascencia-mb** [comment]
[clabot:check]

**Comment by qshao-pivotal** [comment]
Does it work properly if you uncomment these parameters? I would recommend remove security related parameters in examples for now to avoid confusion since it's not supported.

**Comment by qshao-pivotal** [comment]
> @qshao-pivotal
> 
> > recommend remove security related parameters in examples for now to avoid confusion since it's not supported.
> 
> What is not supported?

Any auth, security related thing is not supported.

**Comment by mplascencia-mb** [comment]
@qshao-pivotal @gAmUssA I'm not sure how to proceed on this PR.  Should I close this PR?

**Comment by gAmUssA** [comment]
> Any auth, security related thing is not supported.
not supported where? kafka supports that. we don't have example in this repo but it's not fair to say it's not supported.

Thank you

**Comment by qshao-pivotal** [comment]
> > Any auth, security related thing is not supported.
> > not supported where? kafka supports that. we don't have example in this repo but it's not fair to say it's not supported.
> 
> Thank you

Any auth, security related feature is not implemented in this helm chart repo, thus you can't deploy KSQL successfully if you uncomment the params specified in this PR. What's the point of saying kafka supports it?

**Comment by qshao-pivotal** [comment]
@mplascencia-mb yes please close it since we have `configurationOverrides` and a commented example already.

**Comment by mplascencia-mb** [comment]
Closing this PR due to recommendations that auth/security parameters should not be included in the source helm charts.

**Pull request closed without merging**
