### PR TITLE
Env variables for charts

### PR DESCRIPTION
**Pull request by maver1ck**

### CODE REVIEW

**Comment by maver1ck** [comment]
Ad 1)
I used this as an example.
https://github.com/helm/charts/tree/master/stable/kibana
Ad 2)
OK. 
Ad 3) 
Why ? 
Normally when adding new functionality to helm charts it's needed to bump version (at least in official repo)

PS. Where is Issues page ?

**Comment by maver1ck** [comment]
@qshao-pivotal 
I didn't have time before to finish this PR but I think it now can be consider as ready to review.

**Comment by maver1ck** [comment]
ping @gAmUssA

**Comment by qshao-pivotal** [comment]
Actually, could you give an example about having additional env variables in kafka/kafka-schema-registry/kafka-rest/kafka-connect? @gAmUssA is it normal that admins add extra env in kafka broker server?

**Comment by qshao-pivotal** [comment]
Thanks! Merging

**Pull request merged**
