### PR TITLE
Bump versions to 5.1.2

### PR DESCRIPTION
**Pull request by yangxi**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

## How was this patch tested?

(Please explain how this patch was tested. E.g. helm upgrade on minikube, helm install on gke)

### CODE REVIEW

**Review by ewencp — COMMENTED** [review]
What's the process for testing this works, especially since this includes a minor version upgrade? CI seems to just be linting.

**Comment by qshao-pivotal** [comment]
> What's the process for testing this works, especially since this includes a minor version upgrade? CI seems to just be linting.

Not sure...this relies on Confluent's CI/CD and k8s infra.

**Comment by qshao-pivotal** [comment]
Please DO NOT merge PR without getting upvotes, without filling the question "How was this patch tested?"

**Comment by maxzheng** [comment]
@qshao-pivotal Currently, we don't have automated testing for this. You are right that we should at least do some testing before doing major upgrades for a minor version bump. Let me know if you have suggestions. Thanks!

@yangxi Do you mind working with @gAmUssA to come up with some basic sanity testing steps to test this change (and update our release wiki with the info)? Thanks

**Comment by qshao-pivotal** [comment]
A few thoughts:

0. Trigger lint when PR is submitted/updated
1. Trigger PR test with comment(/test) only after approved reviews
2. Jenkins pulls the PR and deploy it on a k8s cluster (does confluent have a k8s env which can be used for this?)
4. Jenkins run `helm test`( reference https://github.com/helm/helm/blob/master/docs/chart_tests.md)
5. Verify the results(logs publicly accessible if possible?)

**Comment by ewencp** [comment]
Linting is already happening on the PR, and for (1), the cost is trivial so there's no point in blocking on approvals and adding to developer workflow overhead.

2-4 was what the various testing comments were referring to as they require more implementation and maintenance overhead, as well as some design and implementation cost re: the actual test command run by `helm test` (if we even decide that is the best way to test this). We have infrastructure where results could be publicly accessible, but beyond all the automation bits, the real question is what the *existing* testing process was. Without those bits automated, there must be some process for validating changes to this repo manually.

**Comment by qshao-pivotal** [comment]
There's actually almost 0 test except [this](https://github.com/confluentinc/cp-helm-charts/blob/master/charts/cp-kafka/templates/tests/canary-pod.yaml)...What I did before was mainly clone -> run it on gke/pks since I need it for a lot PoCs. But definitely we need more.

**Pull request merged**
