### PR TITLE
added node selectors & tolerations

### PR DESCRIPTION
**Pull request by sflandergan**
charts should support node selector and tolerations to assign them to a specific node set.
I added them following the same naming scheme as the official charts

### CODE REVIEW

**Comment by thuandt** [comment]
👍

**Comment by sflandergan** [comment]
@qshao-pivotal I added the documentation to the values.yaml of each sub-chart. I don't know what to add to the README.md though

**Comment by thuandt** [comment]
@sflandergan Should we allow user can control `affinity`?

```
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
```

**Comment by qshao-pivotal** [comment]
> @qshao-pivotal I added the documentation to the values.yaml of each sub-chart. I don't know what to add to the README.md though

Each subchart has a README.md such as 
https://github.com/confluentinc/cp-helm-charts/blob/master/charts/cp-kafka-connect/README.md

I would suggest create a section called `deployment topology` or sth similar and put parameters there.

**Comment by sflandergan** [comment]
@qshao-pivotal please have a look, if the documentation matches your expectation

**Comment by sflandergan** [comment]
@thuandt this is definitely also helpful. But maybe in another PR. Mine is already open for too long time ;)

**Comment by maver1ck** [comment]
@sflandergan 
Could you please solve conflicts ?

**Comment by sflandergan** [comment]
@maver1ck done. Rebased on current master branch

**Pull request merged**
