### PR TITLE
Add Kafka Connect connectors metrics

### PR DESCRIPTION
**Pull request by maver1ck**
Signed-off-by: Maciej Bryński <maciej.brynski@xcaliber.com>

This PR is adding connectors metrics to Kafka Connect JMX exporter

### CODE REVIEW

**Comment by maver1ck** [comment]
ping @qshao-pivotal

**Comment by maver1ck** [comment]
I'm seeing those metrics in Prometheus.
Sample
```
cp_kafka_connect_connect_connector_metrics{app="cp-kafka-connect",connector="connector_name",instance="100.96.3.186:5556",job="kubernetes-pods",kubernetes_namespace="kafka",kubernetes_pod_name="kafka-cp-kafka-connect-6ff4bd9b4d-bsgnj",pod_template_hash="2990685608",release="kafka",status="running",task="1"}
```

**Comment by qshao-pivotal** [comment]
Are there any Grafana dashboard charts related to these metrics?

**Comment by maver1ck** [comment]
Nope.
I'm using this only for alerting. This tells me that there are failed connectors
```
sum(cp_kafka_connect_connect_worker_metrics_task_count)  - sum(cp_kafka_connect_connect_connector_metrics{status="running"}) > 0
```

**Comment by qshao-pivotal** [comment]
Got it! Merging. Thanks for the PR.

**Pull request merged**
