### PR TITLE
Fix listeners bug

### LINKED ISSUE #145: [Kafka] wrong configuration when NodePort is disabled
When NodePort is disabled this configuration is used:
```
  "advertised.listeners": |-
   EXTERNAL://${HOST_IP}:$((31090 + ${KAFKA_BROKER_ID}))
  "listener.security.protocol.map": |-
   PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
```
which make some of the tool not working properly (like kafka-rest)

### PR DESCRIPTION
**Pull request by maver1ck**
Signed-off-by: Maciej Bryński <maciej.brynski@xcaliber.com>

Fixes #145

Additional listeners section should be commented as NodePort is disabled by default

### CODE REVIEW

**Comment by qshao-pivotal** [comment]
Need better description of what bug, what's changed, what's improved after change. Thanks.

**Comment by maver1ck** [comment]
Default configuration configures additional listeners which are not accessible (because node port is not configured)

**Comment by qshao-pivotal** [comment]
Could you verify that everything works as expected when enabling Nodeport? By default NodePort option is disabled although we have the protocol specified. 
https://github.com/confluentinc/cp-helm-charts/blob/master/charts/cp-kafka/values.yaml#L114-L115

**Comment by gAmUssA** [comment]
@maver1ck anu updates?

**Comment by gAmUssA** [comment]
@maver1ck ping

**Pull request closed without merging**
