### PR TITLE
Update prometheus-jmx-exporter imageTag

### PR DESCRIPTION
**Pull request by ElfoLiNk**
Prometheus JMX exporter upgraded to 0.3.1

### CODE REVIEW

**Comment by ElfoLiNk** [comment]
[clabot:check]

**Comment by gAmUssA** [comment]
@ElfoLiNk what is missing in current version of JMX exporter?
also kindly rebase

**Comment by ElfoLiNk** [comment]
Rebased. Mostly performance improvements https://github.com/prometheus/jmx_exporter/releases

**Comment by gAmUssA** [comment]
Thank you @ElfoLiNk

**Pull request merged**
