### PR TITLE
Bump to 5.2.1

### PR DESCRIPTION
**Pull request by mohnishbasha**

### CODE REVIEW

**Comment by gAmUssA** [comment]
i think we should bump chart version as well 

- https://github.com/confluentinc/cp-helm-charts/blob/master/Chart.yaml 
- https://helm.sh/docs/glossary/#chart-version

**Comment by mohnishbasha** [comment]
ping @confluentinc/tools  ping @gAmUssA  ping @mikkin

**Review by xli1996 — APPROVED** [review]

**Comment by mohnishbasha** [comment]
Do you suggest to bump chart version to 5.2.0?
This is specific to 5.2.0 bump, for others the team can do it themselves.

**Comment by DaveSlinn** [comment]
Why was the chart version not updated as per @gAmUssA comment:

> 
> 
> i think we should bump chart version as well
> 
>     * https://github.com/confluentinc/cp-helm-charts/blob/master/Chart.yaml
> 
>     * https://helm.sh/docs/glossary/#chart-version

**Pull request merged**
