### PR TITLE
Change template partial cp-zookeeper.service-name to cp-zookeeper.connect

### PR DESCRIPTION
**Pull request by nixsticks**
## What changes were proposed in this pull request?

Very small change: cp-kafka chart adds the `-headless` suffix for the Zookeeper connection string in `cp-zookeeper.service-name`, and cp-kafka-rest chart adds the suffix in `cp-zookeeper.fullname`. I think it's more intuitive to append `-headless` in `cp-zookeeper.service-name`, and it is a little confusing to have it appended in different places in the two charts. This PR changes the cp-kafka-rest partials to match those in cp-kafka.

## How was this patch tested?

`helm install` on GKE

### CODE REVIEW

**Comment by nixsticks** [comment]
[clabot:check]

**Comment by qshao-pivotal** [comment]
plz resolve the conflict

**Comment by qshao-pivotal** [comment]
plz resolve the conflict

**Comment by nixsticks** [comment]
Sorry I missed this again @qshao-pivotal, conflict should be resolved.

**Pull request merged**
