### PR TITLE
Added imagePullPolicy for Prometheus Jmx Exporter

### LINKED ISSUE #286: Prometheus images don't support pull policy configuration

### PR DESCRIPTION
**Pull request by nicknezis**
Fixes #286 by adding `imagePullPolicy` on the Promtheus JMX containers.

### CODE REVIEW

**Comment by nicknezis** [comment]
[clabot:check]

**Comment by gAmUssA** [comment]
Hi @nicknezis 
Could you explain motivation of this? 
Trying to understand use case.

**Comment by nicknezis** [comment]
Our initial use of the Helm chart was on a corporate internal network in which we preloaded the images. So we were setting the value to `Never`. I've seen many other Helm charts expose the option so it seemed useful. 
https://kubernetes.io/docs/concepts/configuration/overview/#container-images

**Comment by gAmUssA** [comment]
Sounds good.
It looks like you using `IfNotPresent` as default.
It shouldn't break existing behavior.

**Pull request merged**
