### PR TITLE
feat: More K8s configuration options

### PR DESCRIPTION
**Pull request by carlosjgp**
## What changes were proposed in this pull request?

#449 

## How was this patch tested?

Not tested since I realised the differences between this chart and the incubator/schema-registry chart are too many to consider migrating into this one

I've created an issue and a PR soon to implement the same functionality there
https://github.com/helm/charts/issues/23062

### CODE REVIEW

**Comment by carlosjgp** [comment]
:shrug:

**Comment by gitkent** [comment]
@carlosjgp  We are looking at adding priorityClass into zookeeper and possibly other component as well, why is this issue been closed?

**Comment by carlosjgp** [comment]
> @carlosjgp We are looking at adding priorityClass into zookeeper and possibly other component as well, why is this issue been closed?

PR got stale and no feedback was given for almost a year. I thought there was no intention to get it merged
I'm not using this chart anymore or Kafka

I'm happy to restore the branch and reopen the PR if you find it useful...? @gitkent

**Comment by gitkent** [comment]
@carlosjgp Thanks for that. Yes please restore the PR if you can and see how it goes. We also interest to priorityClass definitions available for all the other CP components.

**Pull request closed without merging**
