### PR TITLE
Bump version to CP 5.3.0

### PR DESCRIPTION
**Pull request by dnozay**
## What changes were proposed in this pull request?

Bump docker image tags to 5.3.0

### CODE REVIEW

**Comment by dnozay** [comment]
cc @sdanduConf so these doesn't fall through the cracks.

**Comment by gAmUssA** [comment]
@dnozay LGTM but we also should bump chart version respectively.
Say 0.3.0 version of chart should correspond to 5.3 version of CP.
Thoughts?

**Comment by dnozay** [comment]
@gAmUssA , I am not sure what you mean, do you want me to add an `appVersion` somewhere?
If `cp-helm-charts` is to get a test environment, do we care about anything else other than latest CP version, it'd be confusing (to me at least) to have versions keep changing without any semantic change to `cp-helm-charts`. In other words what "latest" means is a moving target for CP version, but isn't functionally different in the goal : get me a dev CP environment. WDYT?

**Comment by gAmUssA** [comment]
@dnozay make sense to me but many people use this chart «as is» without modification. I may be surprisingly for many people to discover if they update chart for the same version from git they will get new version of  CP.

**Comment by gAmUssA** [comment]
@dnozay I was talking about this guy https://github.com/confluentinc/cp-helm-charts/blob/51ae55d90b479a763d6a9230fa6c4d0ac548c66d/Chart.yaml#L5

**Comment by dnozay** [comment]
Thanks for the review, please merge if/when you approve or let me know if there is anything else I need to fix first. Thank you :)

**Pull request merged**
