### PR TITLE
Add ability to configure zookeeper chroot for installations of cp-kafka and cp-kafka-rest alongside cp-zookeeper

### PR DESCRIPTION
**Pull request by nixsticks**
## What changes were proposed in this pull request?

When the cp-zookeeper chart is installed alongside cp-kafka and cp-kafka-rest, users cannot configure the chroot for Zookeeper. This patch allows users to configure an optional chroot for Zookeeper, e.g. `/kafka`.

## How was this patch tested?

- `helm install --dry-run` to ensure that ZK connection string defaults to no chroot
- Add `zkChroot: /kafka` to `values.yaml` and `helm install --dry-run` to ensure that ZK connection string is amended to include chroot
- Installation on GKE

### CODE REVIEW

**Comment by nixsticks** [comment]
[clabot:check]

**Comment by qshao-pivotal** [comment]
1. @gAmUssA Is it a recommended practice to have a chroot when setting up confluent platform? I'd like to understand why do we need it since this is a dedicated zookeeper per cp-helm-chart installation.

**Comment by qshao-pivotal** [comment]
> Seems to me this is a worthwhile change; we can't assume everyone is using it the same way. Also note that if you're using Y!'s kafka-manager, it creates its own root in ZK.

Could you elaborate more on why a customized chroot is necessary if we install an instance of cp-helm-charts? What improves by using a different chroot other than default?

**Comment by qshao-pivotal** [comment]
@nixsticks How's the chroot created if one is provided in values.yaml? Will it error out if the chroot doesn't exist in zookeeper?

**Comment by qshao-pivotal** [comment]
> Hi @qshao-pivotal! Sorry I didn't see these messages. The chroot is created when Kafka starts up and connects to Zookeeper -- nothing else is needed, I believe. We consider it just good practice to create a chroot (especially if we want to share our ZK with anything else) -- I don't think it's necessary, just something nice to allow clients to configure.

1. cp-helm-chart installation will be 1-to-1 mapping between Kafka and Zookeeper
2. to install multiple cp-kafka with a shared zookeeper having different chroots, the recommended way is to provide `zookeeper url` param in cp-kafka's `values.yaml`

I believe current chart structure has already provided what's needed.

**Pull request closed without merging**
