### PR TITLE
Add support for custom pod annotations

### PR DESCRIPTION
**Pull request by mixja**
This PR adds support to add annotations to the pod spec for the cp-kafka-connect component.

I specifically required this to be able to use kiam to assign an IAM role to the pod that granted the S3 sink connector permissions to write to an S3 bucket.  An example of this configuration is below:

```
cp-kafka-connect:
  annotations:
    iam.amazonaws.com/role: <role-arn>
```

### CODE REVIEW

**Comment by qshao-pivotal** [comment]
There's [one](https://github.com/confluentinc/cp-helm-charts/commit/c2acb098f94a09c30013b20ce56c7a8ebf1a05ac) existing already. :)

**Comment by mixja** [comment]
Yes I did that one as well, but that's for external service annotations.

This one is for pod annotations - for my use case the connect pod requires S3 permissions for S3 sink connector hence my PR.  Happy to also extend this PR to other pods if you want.

**Comment by qshao-pivotal** [comment]
> Yes I did that one as well, but that's for external service annotations.
> 
> This one is for pod annotations - for my use case the connect pod requires S3 permissions for S3 sink connector hence my PR. Happy to also extend this PR to other pods if you want.

Ah! It would be nice to have it added on other subcharts, maybe with a more specific name like `podannotations`,etc. :)

**Comment by mixja** [comment]
@qshao-pivotal - I have made the changes as requested

**Pull request merged**
